global:
  labels:
    app: cmstate-webhook
  annotations: {}

serviceAccount:
  create: true
  name: cmstate-operator-webhook-sa

image:
  repository: public.ecr.aws/x4a1o1q2/cmstate-operator-webhook
  tag: latest
  pullPolicy: IfNotPresent

deployment:
  labels: {}
  annotations: {}
  pod:
    labels: {}
    annotations: {}

service:
  name: "cmstate-operator-service"
  labels: {}
  annotations: {}

namespace:
  create: true
  name: cmstate-operator-webhook

rbac:
  create: true
  role:
    name: cmstate-operator-role
    rules:
      - apiGroups: [""]
        resources: ["pods"]
        verbs: ["get", "list", "watch"]
