apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace:  {{ include "chart.namespaceName" .}}
  labels:
    {{- if or .Values.global.labels .Values.service.labels }}
    {{ toYaml .Values.global.labels . | nindent 4 }}
    {{ toYaml .Values.service.labels . | nindent 4 }}
    {{- end }}
spec:
  selector:
    {{- if or .Values.global.labels .Values.deployment.pod.labels }}
    {{ toYaml .Values.global.labels . | nindent 4 }}
    {{ toYaml .Values.deployment.pod.labels . | nindent 4 }}
    {{- end }}
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8443
