apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace:  {{ .Release.Namespace }}
  labels:
    {{- if or .Values.global.labels }}
    {{ toYaml .Values.global.labels | nindent 4 }}
    {{- end }}
    {{- if .Values.service.labels }}
    {{ toYaml .Values.service.labels | nindent 4 }}
    {{- end }}
spec:
  selector:
    {{- if or .Values.global.labels }}
    {{ toYaml .Values.global.labels | nindent 4 }}
    {{- end }}
    {{- if .Values.deployment.pod.labels }}
    {{ toYaml .Values.deployment.pod.labels | nindent 4 }}
    {{- end }}
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8443
